/* eslint-disable no-undef */
module.exports = [
  { value: '✨ feat', name: '特性: 新的特性' },
  { value: '🐛 fix', name: '修复: 修复Bug' },
  { value: '📚 docs', name: '文档: 变更的只有文档' },
  { value: '💅 style', name: '格式: 空格、分号等格式修复' },
  { value: '♻️ refactor', name: '重构: 代码重构，注意和特性、修复区分开' },
  { value: '⚡️ perf', name: '性能: 提升性能' },
  { value: '💩 optimize', name: '优化: 代码优化' },
  { value: '⚰️ dead', name: '删除: 废弃代码' },
  { value: '🚧 wip', name: '开发中: 尚未完成' },
  { value: '🏷️ i18n', name: '国际化: 多语言国际化相关更改' },
  { value: '🚀 chore', name: '工具: 开发工具变动 (构建、脚手架工具等)' },
  { value: '🔒 security', name: '安全性更新: 安全性修复或更新' },
  { value: '🖌️ ui', name: '用户界面: 调整和更改' },
  { value: '⚙️ config', name: '配置: 配置文件的更改' },
  { value: '🛠️ deps', name: '依赖更新: 更新依赖库或包' },
  { value: '📡 deploy', name: '部署: 与项目部署相关的更改' },
  { value: '📂 file', name: '文件操作: 添加、删除、移动文件' },
  { value: '🥚 egg', name: '彩蛋: 小惊喜' },
  { value: '🌐 network', name: '网络: 网络请求、通信相关的更改' },
  { value: '✅ test', name: '测试: 添加一个测试' },
  { value: '⚗️ experiments', name: '实验性: 实验性功能，可能存在错误等未知问题' },
  { value: '🛠️ workflows', name: '工作流: 工作流相关文件更改' },
  { value: '💻 dev', name: '开发环境: 开发工具、环境配置更改' },
  { value: '🏭 prod', name: '生产环境: 生产环境配置更改' },
  { value: '📝 changelog', name: '更新日志: 更新 changelog' },
  { value: '⏪ revert', name: '回滚: 代码回退' },
  { value: '⌛ merge', name: '合并: 合并代码' },
  { value: '📦 build', name: '打包: 打包发布' },
  { value: '🍻 release', name: '发布: 发布新版本' }
];
