name: ci

# 当推送到 main分支 时 触发此工作流
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@main

      # 全局安装 pnpm
      - name: install pnpm
        run: npm install -g pnpm

      # 使用 pnpm 安装依赖
      - name: install dependencies
        run: pnpm install

      # 使用 pnpm 执行测试
      - name: run tests
        run: pnpm test:ci

      # 上传覆盖率报告到 Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          path-to-lcov: coverage/lcov.info

      # 同步到 Gitee
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:kwooshung/standard-version-helper.git'
          destination-repo: 'git@gitee.com:kwooshung/standard-version-helper.git'

  finish:
    needs: build-and-deploy
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@main
        with:
          parallel-finished: true
          carryforward: 'run-1,run-2'
