name: JestTest

# 当推送到 develop分支时 触发此工作流
on:
  push:
    branches:
      - develop

jobs:
  test:
    name: create system
    runs-on: ubuntu-latest

    steps:
      # 使用最新版本的actions/checkout
      - name: checkout
        uses: actions/checkout@main

      # 全局安装 pnpm
      - name: install pnpm
        run: npm install -g pnpm

      # 使用 pnpm 安装依赖
      - name: install dependencies
        run: pnpm install

      # 使用 pnpm 执行测试
      - name: run tests
        run: pnpm test:ci
